#management:
#  health:
#    circuitbreakers:   # ?????
#      enabled: true
#    ratelimiters:
#      enabled: true    # ????? ?? ??
#    redis:
#      enabled: false
#  endpoints:                # ???
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always # ?? ??

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: rule-service
          uri: lb://rule-service
          predicates:
            - Path=/api/rule/v1/**
            #- Host=**.example.com ??
          filters:
            #- SetPath=/?????
server:
  port: 9000


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${custom.server}:8761/eureka/

custom:
  server: ENC(w10K+s4EnEwDbAxgBF+dbNEpajaAseXA)

jasypt:
  encryptor:
    password:
    bean: jasyptStringEncryptor
