#management:
#  health:
#    circuitbreakers:   # ?????
#      enabled: true
#    ratelimiters:
#      enabled: true    # ????? ?? ??
#    redis:
#      enabled: false
#  endpoints:                # ???
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always # ?? ??

spring:
  profiles:
    default:

  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: rule-service
          uri: lb://rule-service
          predicates:
            - Path=/api/rule/v1/**
            #- Host=**.example.com ??
          filters:
            #- SetPath=/?????

        - id: baeker-member
          uri: lb://baeker-member
          predicates:
            - Path=/api/member/**

server:
  port: 9000


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${custom.server}:8761/eureka/

custom:
  server: 127.0.0.1

jasypt:
  encryptor:
    password:
    bean: jasyptStringEncryptor
