#management:
#  health:
#    circuitbreakers:   # ?????
#      enabled: true
#    ratelimiters:
#      enabled: true    # ????? ?? ??
#    redis:
#      enabled: false
#  endpoints:                # ???
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always # ?? ??

spring:
  cloud:
    gateway:
      routes:
        - id: rule-service
          uri: lb://rule-service
          predicates:
            - Path=/api/rule/v1/**
            #- Host=**.example.com ??
          filters:
            #- SetPath=/?????
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/