spring:
  config:
    activate:
      on-profile: dev

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: ENC(ebfNAD4t/e7tlS39HOlQyAEP+mqX4uAL)
    key-store: keystore.p12