management:
  health:
    redis:
      enabled: false

spring:
  cloud:
    gateway:
      routes:
        - id: route1
          uri: # ??? ?? ??
          predicates:
            #- Path=/?????
            #- Host=**.example.com ??
          filters:
            #- SetPath=/?????